# Use an OpenJDK image for Java applications
FROM openjdk:17-jdk-slim AS build

# Set the working directory in the container
WORKDIR /examination-service

# Copy the Maven wrapper and pom.xml files
COPY mvnw pom.xml /examination-service/
COPY .mvn /examination-service/.mvn

# Check the contents of /examination-service after copying
RUN echo "Contents of /examination-service:" && ls -la /examination-service

# Ensure Maven wrapper script is executable within the container
RUN chmod +x /examination-service/mvnw

# Verify that mvnw is executable
RUN echo "Permissions of mvnw:" && ls -la /examination-service/mvnw

# Install dependencies without running tests to leverage Docker layer caching
RUN ./mvnw dependency:go-offline -B

# Copy the source code
COPY src /examination-service/src

# Package the application with Maven
RUN ./mvnw clean package -DskipTests

# List the contents of the target directory
RUN ls -la /examination-service/target

# Start a new image to reduce the size of the final image
FROM openjdk:17-jdk-slim

# Set the working directory and copy the jar file from the build stage
WORKDIR /gateway-api
COPY --from=build /examination-service/target/examinationService-0.0.1-SNAPSHOT.jar /examination-service/baby-monitor.jar

# Run the application
CMD ["java", "-jar", "/examination-service/baby-monitor.jar"]